### ISSUE TITLE
Create 6.0.6: ComputerEvent crash and parallel repackaging not working

### ISSUE THREAD

**Issue by CC-Cabin** [cshawny/god-damn-repackager#1]
Hi! I’m trying to use God Damn Repackager 0.5.1 Forge Alpha on Minecraft 1.20.1 with Create 6.0.6.

The mod page states compatibility with Create 6.0.x (tested on 6.0.8), so I tried using it with 6.0.6. I encountered two issues.

Environment

* Minecraft: 1.20.1
* Forge: 47.4.0
* Create: 6.0.6
* God Damn Repackager: 0.5.1 Forge Alpha
* Dedicated server

Issue 1 — Server crash when a Repackager is ticked

With the original GDR 0.5.1 jar, the server starts successfully, but crashes after I join and the relevant Repackager is loaded/ticked.

The important part of the crash is:
```
java.lang.NoClassDefFoundError:
com/simibubi/create/compat/computercraft/events/ComputerEvent
```

The exception originates from GDR’s Repackager logic, around tryPartialTakeover.

Create 6.0.6 does not appear to contain:
`com.simibubi.create.compat.computercraft.events.ComputerEvent`

This looks like an API/class difference between Create 6.0.6 and the tested Create 6.0.8 environment.

Issue 2 — Parallel Repackagers do not work after bypassing the ComputerCraft event

For testing purposes, I made a local compatibility build of GDR 0.5.1 which only bypasses the ComputerCraft ComputerEvent / RepackageEvent notification code. The actual SharedPackagePool.deposit(...) logic was left intact.

This prevents the crash and the server runs normally.

However, the main parallel-repackaging feature does not appear to work on Create 6.0.6.

I tested with:

* a newly placed Item Vault
* multiple newly placed Repackagers connected to the same Vault
* each Repackager individually receiving a redstone signal
* a new order large enough to require multiple packages

Only one Repackager works. The other Repackagers remain idle.

I also tried replacing the Vault and Repackagers after installing GDR, with the same result.

Expected behavior

Multiple Repackagers connected to the same Vault should consume packages from the shared package pool and work in parallel.

Actual behavior

With stock GDR 0.5.1 + Create 6.0.6:
```
Repackager tick
→ NoClassDefFoundError: ComputerEvent
→ server crash
```

Additional investigation

I checked the patched bytecode to make sure the compatibility patch wasn’t skipping the shared package pool.

PartialRepackager.deposit() still reaches:
`SharedPackagePool.get(server).deposit(vaultId, packages)`

and the parallel feeding logic containing:
`SharedPackagePool.poll(vaultId)`

is still present.

I also confirmed that the relevant queuedExitingPackages.addAll(...) call exists in Create 6.0.6’s repackaging path.

So I suspect there may be another behavioral/API difference between Create 6.0.6 and 6.0.8 besides ComputerEvent.

Questions

1. Is Create 6.0.6 actually intended to be supported by GDR 0.5.1, or is 6.0.8 effectively the minimum supported Create 6.x version?
2. If 6.0.6 is intended to work, is there another known API/behavior difference that would prevent sibling Repackagers from polling the shared package pool?
3. Would it be feasible to make the ComputerCraft event integration optional/fallback-safe so GDR can run on Create versions that don’t have ComputerEvent?

I’m happy to provide the full crash report, latest.log, the Create 6.0.6 jar/version details, or test a debug/dev build if that would help.

Thanks!
